services:
  web-app:
    build: .
    container_name: express-compose-app
    expose:
      - "5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://myuser:mypassword@db-postgres:5432/mydb 
    depends_on:
      - db-postgres 
      - redis-cache

#postgesql 
  db-postgres:
    image: postgres:16-alpine 
    container_name: postgres-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser      
      - POSTGRES_PASSWORD=mypassword 
      - POSTGRES_DB=mydb           
    volumes:
      - pgdata:/var/lib/postgresql/data 


# Nginx Service 
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy-container
    ports:
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro 
      - ./nginx/error503.html:/usr/share/nginx/html/error503.html:ro
    depends_on:
      - web-app 
    restart: always

  # Redis Service
  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache-container
    ports:
      - "6379:6379" 
    restart: always



volumes:
  pgdata:
